# Generated by Django 5.0.7 on 2024-07-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_nacionality_actor_nationality'),
        ('genres', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
